---
- name: 'Build Image and run container with ansible playbook'
  hosts: localhost
  tasks:
    - name: stop running container
      command: docker stop react_app_container
      ignore_errors: yes

    - name: remove stopped container
      command: docker rm react_app_container
      ignore_errors: yes

    - name: remove used image
      command: docker rmi hazemsoliman9/react-app
      ignore_errors: yes

    - name: build docker image from dockerfile
      command: docker build -t hazemsoliman9/react-app .

    - name: push image to dockerhub
      command: docker push hazemsoliman9/react-app

    - name: run container from image
      command: docker run -d -p 3000:3000 --name react_app_container hazemsoliman9/react-app
